name: Maven CI/CD

on:
 push:
    branches: [ main ]

jobs:
  publish-job:
      runs-on: ubuntu-latest
      needs: [build_and_test]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 14
        - run: mvn -B package --file pom.xml -DskipTests
        - run: cp target/*jar-with-dependencies.jar ./
        - uses: actions/upload-artifact@v1
          with:
            name: Package
           
            